#!/bin/sh

set -eu

openclaw_user="${OPENCLAW_USER:-openclaw}"
openclaw_service="${OPENCLAW_SERVICE:-openclaw-gateway.service}"
user_id="$(id -u "$openclaw_user")"
openclaw_home="$(getent passwd "$openclaw_user" | cut -d: -f6)"
[ -n "$openclaw_home" ]

runuser --user "$openclaw_user" -- \
    env "HOME=${openclaw_home}" "XDG_RUNTIME_DIR=/run/user/${user_id}" \
    systemctl --user is-active --quiet "$openclaw_service"
runuser --user "$openclaw_user" -- \
    env "HOME=${openclaw_home}" "XDG_RUNTIME_DIR=/run/user/${user_id}" \
    openclaw --version |
    sed -n 's/.*\([0-9][0-9][0-9][0-9]\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/p' |
    head -n 1
