#!/bin/sh

set -eu

case "${SSH_ORIGINAL_COMMAND:-}" in
    heartbeat)
        exec sudo -n /usr/local/sbin/production-heartbeat
        ;;
    alert)
        exec sudo -n /usr/local/sbin/production-monitor-relay
        ;;
    *)
        printf '%s\n' 'Unsupported production monitoring request.' >&2
        exit 2
        ;;
esac
